/**
 * REMOTE VIEWING — Coordinate Remote Viewing protocol, honestly implemented.
 *
 * ===================================================================
 * INTERFACE (this is what main.js wires up)
 * ===================================================================
 *
 *   import { RemoteViewRun, STAGES, TRIALS, CHANCE } from './modes/remoteview.js';
 *
 *   const run = new RemoteViewRun(ctx, opts);
 *   const { coordinate } = await run.begin();   // seals the target; MUST be awaited first
 *   run.mountUI(hostEl);                        // builds the whole stage UI inside hostEl
 *   const report = await run.finish();          // resolves when the viewer commits a ranking
 *   run.dispose();
 *
 *   ctx   = { scene, particles, floatText, director, tweens, onUpdate }
 *           Every field is optional — the mode is DOM-first and only uses the 3D
 *           juice if it is handed some. onUpdate(snapshot) fires on every stage
 *           change and every ranking change.
 *   opts  = {
 *     pool:        Target[]  (default TARGETS from ../data/targets.js)
 *     candidates:  5         how many targets the ranking stage shows
 *     ideogramMs:  9000      soft window for the reflexive stroke
 *     autoLog:     true      finish() writes the session to the career log itself
 *     onStage:     fn(stageId, index)
 *   }
 *
 *   report() — same shape as ZenerRun.report(): everything summarize() returns,
 *   plus mode/results/durationMs/proof, plus the remote-viewing specifics
 *   (coordinate, target, candidates, ranking, impressions, sketches).
 *
 *   Also exported: STAGES (the default stage list), TRIALS, CHANCE,
 *   SENSORY_CATEGORIES, buildRevealBlock(report) → an element for the result
 *   modal, and verifyRun(report) → re-checks the commitment.
 *
 * ===================================================================
 * PROTOCOL — the part that must not be fudged
 * ===================================================================
 *
 * 1. COORDINATE. An 8-digit reference is generated by randomCoordinate(), which
 *    is pure CSPRNG output. It is generated BEFORE the target is drawn and the
 *    target is never derived from it, hashed with it, or indexed by it — see
 *    begin(), where the ordering makes the independence structural rather than
 *    a promise. The coordinate is a LABEL, exactly as in the original protocol:
 *    it carries no information whatsoever about what the target is. Two runs
 *    with the same coordinate would be two independent draws.
 *
 * 2. SEALED BEFORE THE SESSION. The target and the whole candidate set are
 *    chosen, then committed with SHA-256 via seal() before mountUI() can paint
 *    anything and before the viewer records a single impression. The salt is
 *    published in the report at the end, so anyone can recompute
 *    SHA-256(salt + ":" + payload) and prove the target did not change after
 *    the ranking. Same guarantee zener.js gives, same code path.
 *
 * 3. FAIR CANDIDATES. chooseTargetSet() in ../data/targets.js draws the true
 *    target uniformly from the pool, the decoys uniformly WITHOUT REPLACEMENT
 *    from the pool minus the true target, and then shuffles the display order
 *    independently with Fisher-Yates. So: a decoy is never the true target, no
 *    target appears twice, and grid position leaks nothing. Chance of a
 *    first-place hit is exactly 1/5 = 20%.
 *
 * 4. NO Math.random ANYWHERE THAT MATTERS. Every draw goes through core/rng.js
 *    (crypto.getRandomValues with rejection sampling). Math.random appears in
 *    this file exactly once, for the cosmetic position jitter of a particle
 *    burst, and is labelled where it happens.
 *
 * 5. NO ADAPTIVE DIFFICULTY. The pool, the candidate count and the chance level
 *    are constants. Nothing in this file reads the career log, the current
 *    score, or any history before choosing a target. A run cannot be made
 *    easier or harder by how the viewer has been doing.
 *
 * 6. SCORING. A hit is ranking the true target FIRST. Anything else is a miss.
 *    trials = 1, hits ∈ {0,1}, chance = 0.2. Second place is reported for
 *    interest but is NOT scored, because scoring it would change the null and
 *    the honest p-value with it.
 */
import * as THREE from 'three';
import { randomCoordinate } from '../core/rng.js';
import { seal, verify } from '../core/commit.js';
import { summarize } from '../core/stats.js';
import { logSession } from '../core/store.js';
import { TARGETS, CANDIDATES, chooseTargetSet, paintTarget } from '../data/targets.js';
import { Sketchpad, padTools } from '../ui/sketchpad.js';
import * as audio from '../juice/audio.js';
import '../ui/rv.css';

/** One ranking trial per session. */
export const TRIALS = 1;
/** Exactly 1/5: five candidates, one correct, ranked first or not. */
export const CHANCE = 1 / CANDIDATES;
export const MODE = 'rv';

/** The default stage list, in protocol order. */
export const STAGES = [
  {
    id: 'ideogram', label: 'Ideogram', title: 'Stage I — Ideogram',
    sub: 'Pen on paper, no thinking',
    lede: 'Hold the coordinate in mind and let your hand move <b>once</b>, fast, without deciding what to draw. ' +
          'The ideogram is a reflex, not a picture. A few seconds is all it gets.',
  },
  {
    id: 'sensory', label: 'Sensory', title: 'Stage II — Sensory Impressions',
    sub: 'Raw data, no conclusions',
    lede: 'Tag whatever comes through. Single words only — <b>textures, colours, temperature, sound, smell, size</b>. ' +
          'Do not try to name the place; naming is analysis, and analysis is noise.',
  },
  {
    id: 'sketch', label: 'Sketch', title: 'Stage III — Sketch',
    sub: 'Put the shape down',
    lede: 'Draw what the impressions add up to. Shapes, edges, horizons, where things sit relative to each other. ' +
          'It does not need to be good — it needs to be <b>yours</b>.',
  },
  {
    id: 'ranking', label: 'Rank', title: 'Stage IV — Ranking',
    sub: 'One of these five is the target',
    lede: 'Five candidates, drawn before you started and sealed. Rank them against your own notes — ' +
          'first place is your call on the target. By chance alone you are right <b>one time in five</b>.',
  },
];

/** Quick-pick vocabulary. Free text is always allowed alongside. */
export const SENSORY_CATEGORIES = [
  { id: 'textures', name: 'Textures', chips: ['rough', 'smooth', 'grainy', 'wet', 'dry', 'soft', 'hard', 'jagged', 'slick', 'crumbly', 'fibrous', 'metallic'] },
  { id: 'colours', name: 'Colours', chips: ['white', 'black', 'grey', 'blue', 'green', 'brown', 'red', 'orange', 'yellow', 'gold', 'turquoise', 'violet'] },
  { id: 'temperature', name: 'Temperature', chips: ['cold', 'cool', 'mild', 'warm', 'hot', 'burning', 'damp cold', 'dry heat'] },
  { id: 'sounds', name: 'Sounds', chips: ['silence', 'rushing', 'roaring', 'wind', 'dripping', 'voices', 'machinery', 'birds', 'creaking', 'crashing', 'echo', 'traffic'] },
  { id: 'smells', name: 'Smells & Tastes', chips: ['salt', 'smoke', 'damp earth', 'vegetation', 'sulphur', 'chemical', 'dust', 'sea air', 'pine', 'cooking', 'ozone', 'nothing'] },
  { id: 'dimensions', name: 'Dimensions', chips: ['tall', 'low', 'wide', 'narrow', 'deep', 'enclosed', 'open', 'vast', 'flat', 'layered', 'vertical', 'massive'] },
];

const ORDINAL = ['', '1st', '2nd', '3rd', '4th', '5th'];

const el = (tag, cls, html) => {
  const n = document.createElement(tag);
  if (cls) n.className = cls;
  if (html != null) n.innerHTML = html;
  return n;
};

/** ?turbo=N shortens waits for automated testing. It never touches the odds. */
function turboFactor() {
  try {
    const t = Number(new URLSearchParams(globalThis.location?.search || '').get('turbo'));
    return Number.isFinite(t) && t > 0 ? t : 1;
  } catch { return 1; }
}

export class RemoteViewRun {
  constructor(ctx = {}, opts = {}) {
    this.ctx = ctx || {};
    this.pool = opts.pool || TARGETS;
    this.candidateCount = opts.candidates ?? CANDIDATES;
    this.ideogramMs = (opts.ideogramMs ?? 9000) / turboFactor();
    this.autoLog = opts.autoLog !== false;
    this.onStage = opts.onStage || null;
    this.stages = opts.stages || STAGES;

    this.chance = 1 / this.candidateCount;
    this.startedAt = Date.now();
    this.stageIndex = 0;
    this.stageEnteredAt = Date.now();
    this.stageTimes = {};

    this.coordinate = null;
    this.target = null;
    this.decoys = null;
    this.order = null;
    this.commitment = null;

    this.impressions = Object.fromEntries(SENSORY_CATEGORIES.map((c) => [c.id, []]));
    this.ranking = new Map();     // target id -> rank (1..n)
    this.committed = false;
    this.finished = false;
    this.hits = 0;

    this.pads = {};
    this._nodes = {};
    this._timer = null;
    this._keyHandler = null;
    this._done = new Promise((res) => { this._resolveDone = res; });
  }

  /* ================================================================
   * begin() — draw, commit, then hand back the coordinate
   * ================================================================ */

  /**
   * Chooses the candidate set and seals it. Nothing may be displayed before
   * this resolves. Returns { coordinate, sealShort }.
   */
  async begin() {
    if (this.commitment) return { coordinate: this.coordinate, sealShort: this.commitment.short };

    // (1) The coordinate first, from the CSPRNG, with no target in existence
    //     yet. It therefore cannot encode anything about the target: there is
    //     nothing to encode at the moment it is generated. This ordering is the
    //     guarantee — not a convention we could quietly break later.
    this.coordinate = randomCoordinate();

    // (2) Now the draw. Uniform target; decoys uniform without replacement from
    //     the pool minus the target; display order shuffled independently.
    const set = chooseTargetSet(this.pool, this.candidateCount);
    this.target = set.target;
    this.decoys = set.decoys;
    this.order = set.order;

    // (3) Seal the whole set — the target AND the display order — before the
    //     viewer sees or records anything. The salt is published in report().
    const payload = [
      `rv:${this.coordinate}`,
      `target=${this.target.id}`,
      `candidates=${this.order.map((t) => t.id).join(',')}`,
    ].join(':');
    this.commitment = await seal(payload);
    this.sealedAt = this.commitment.sealedAt;

    return { coordinate: this.coordinate, sealShort: this.commitment.short };
  }

  /* ================================================================
   * UI
   * ================================================================ */

  mountUI(hostEl) {
    if (!this.commitment) throw new Error('RemoteViewRun: await begin() before mountUI()');
    if (!hostEl) throw new Error('RemoteViewRun: mountUI needs a host element');
    this.host = hostEl;

    const root = el('div', 'rv-root');
    root.innerHTML = `
      <div class="rv-head">
        <div class="rv-coord">
          <span class="rv-coord-k">Coordinate</span>
          <span class="rv-coord-v t-mono" id="rv-coord"></span>
        </div>
        <div class="rv-seal">
          <span class="rv-seal-k">Target sealed</span>
          <code id="rv-seal"></code>
        </div>
      </div>
      <ol class="rv-rail" id="rv-rail"></ol>
      <div class="rv-stages" id="rv-stages"></div>
      <div class="rv-foot">
        <p class="rv-hint" id="rv-hint"></p>
        <div class="rv-actions">
          <button type="button" class="btn ghost rv-back" id="rv-prev">Back</button>
          <button type="button" class="btn" id="rv-next">Next</button>
        </div>
      </div>
    `;
    hostEl.appendChild(root);
    this.root = root;

    root.querySelector('#rv-coord').textContent = this.coordinate;
    root.querySelector('#rv-seal').textContent = this.commitment.short;

    const rail = root.querySelector('#rv-rail');
    this.stages.forEach((s, i) => {
      const li = el('li', 'rv-rail-item');
      li.appendChild(el('span', 'rv-rail-bar'));
      li.appendChild(el('span', 'rv-rail-label', s.label));
      li.dataset.i = String(i);
      rail.appendChild(li);
    });
    this._nodes.rail = rail;

    const stages = root.querySelector('#rv-stages');
    this._nodes.stages = stages;
    stages.appendChild(this._buildIdeogram());
    stages.appendChild(this._buildSensory());
    stages.appendChild(this._buildSketch());
    stages.appendChild(this._buildRanking());

    this._nodes.hint = root.querySelector('#rv-hint');
    this._nodes.prev = root.querySelector('#rv-prev');
    this._nodes.next = root.querySelector('#rv-next');
    this._nodes.prev.addEventListener('click', () => this.prevStage());
    this._nodes.next.addEventListener('click', () => this.nextStage());

    // Pads must be in the DOM before they can measure themselves.
    this.pads.ideogram.mount();
    this.pads.sketch.mount();

    this._keyHandler = (e) => this._onKey(e);
    globalThis.addEventListener('keydown', this._keyHandler);

    this._goto(0, true);
    return root;
  }

  /* ---------- stage I: ideogram ---------- */

  _buildIdeogram() {
    const s = this.stages[0];
    const wrap = el('section', 'rv-stage');
    wrap.dataset.stage = 'ideogram';
    wrap.appendChild(el('h2', 'rv-title', `${s.title}<small>${s.sub}</small>`));
    wrap.appendChild(el('p', 'rv-lede', s.lede));

    const pad = new Sketchpad({
      label: 'Ideogram',
      minWidth: 2.2, maxWidth: 7.5, grid: false,
      onChange: () => { this._syncControls(); this._onUpdate(); },
    });
    pad.el.classList.add('rv-ideogram');
    this.pads.ideogram = pad;
    wrap.appendChild(pad.el);
    wrap.appendChild(padTools(pad));

    const timer = el('div', 'rv-timer');
    timer.appendChild(el('div', 'rv-timer-fill'));
    wrap.appendChild(timer);
    const cd = el('p', 'rv-countdown', 'Window <b>—</b>');
    wrap.appendChild(cd);
    this._nodes.timer = timer;
    this._nodes.countdown = cd;
    return wrap;
  }

  _startIdeogramTimer() {
    this._stopTimer();
    const total = this.ideogramMs;
    const t0 = performance.now();
    const fill = this._nodes.timer.querySelector('.rv-timer-fill');
    this._nodes.timer.classList.remove('spent');
    const tick = () => {
      const k = Math.min(1, (performance.now() - t0) / total);
      fill.style.transform = `scaleX(${(1 - k).toFixed(3)})`;
      const left = Math.max(0, Math.ceil((total * (1 - k)) / 1000));
      this._nodes.countdown.innerHTML = k >= 1
        ? 'Window <b>closed</b> — that is long enough'
        : `Window <b>${left}s</b>`;
      if (k >= 1) {
        this._nodes.timer.classList.add('spent');
        this._stopTimer();
      }
    };
    tick();
    this._timer = setInterval(tick, 100);
  }

  _stopTimer() {
    if (this._timer) { clearInterval(this._timer); this._timer = null; }
  }

  /* ---------- stage II: sensory ---------- */

  _buildSensory() {
    const s = this.stages[1];
    const wrap = el('section', 'rv-stage');
    wrap.dataset.stage = 'sensory';
    wrap.appendChild(el('h2', 'rv-title', `${s.title}<small>${s.sub}</small>`));
    wrap.appendChild(el('p', 'rv-lede', s.lede));

    const cats = el('div', 'rv-cats');
    for (const cat of SENSORY_CATEGORIES) {
      const c = el('div', 'rv-cat');
      const head = el('div', 'rv-cat-head');
      head.appendChild(el('span', 'rv-cat-name', cat.name));
      const count = el('span', 'rv-cat-count', '');
      head.appendChild(count);
      c.appendChild(head);

      const chips = el('div', 'rv-chips');
      for (const word of cat.chips) chips.appendChild(this._makeChip(cat.id, word, chips, count));
      c.appendChild(chips);

      const row = el('div', 'rv-freerow');
      const input = el('input', 'rv-free');
      input.type = 'text';
      input.maxLength = 28;
      input.placeholder = `your own word for ${cat.name.toLowerCase()}…`;
      input.setAttribute('aria-label', `Add your own ${cat.name}`);
      const add = el('button', 'btn small rv-add', 'Add');
      add.type = 'button';
      const commitWord = () => {
        const word = input.value.trim().toLowerCase().slice(0, 28);
        input.value = '';
        if (!word) return;
        if (this.impressions[cat.id].includes(word)) return;
        const chip = this._makeChip(cat.id, word, chips, count, true);
        chips.appendChild(chip);
        chip.click();                 // a word you typed is a word you meant
      };
      add.addEventListener('click', commitWord);
      input.addEventListener('keydown', (e) => {
        if (e.key === 'Enter') { e.preventDefault(); e.stopPropagation(); commitWord(); }
      });
      row.appendChild(input);
      row.appendChild(add);
      c.appendChild(row);
      cats.appendChild(c);
    }
    wrap.appendChild(cats);
    return wrap;
  }

  _makeChip(catId, word, chipsEl, countEl, own = false) {
    const b = el('button', `rv-chip${own ? ' rv-own' : ''}`, word);
    b.type = 'button';
    b.setAttribute('aria-pressed', 'false');
    b.addEventListener('click', () => {
      const list = this.impressions[catId];
      const i = list.indexOf(word);
      if (i >= 0) { list.splice(i, 1); b.classList.remove('on'); b.setAttribute('aria-pressed', 'false'); }
      else { list.push(word); b.classList.add('on'); b.setAttribute('aria-pressed', 'true'); if (audio.ready()) audio.sfxHover(); }
      countEl.textContent = list.length ? `${list.length} tagged` : '';
      countEl.classList.toggle('has', list.length > 0);
      this._syncControls();
      this._onUpdate();
    });
    return b;
  }

  /* ---------- stage III: sketch ---------- */

  _buildSketch() {
    const s = this.stages[2];
    const wrap = el('section', 'rv-stage');
    wrap.dataset.stage = 'sketch';
    wrap.appendChild(el('h2', 'rv-title', `${s.title}<small>${s.sub}</small>`));
    wrap.appendChild(el('p', 'rv-lede', s.lede));

    const pad = new Sketchpad({
      label: 'Sketch',
      minWidth: 1.4, maxWidth: 5.4, grid: true,
      onChange: () => { this._syncControls(); this._onUpdate(); },
    });
    pad.el.classList.add('rv-sketch');
    this.pads.sketch = pad;
    wrap.appendChild(pad.el);
    wrap.appendChild(padTools(pad));
    return wrap;
  }

  /* ---------- stage IV: ranking ---------- */

  _buildRanking() {
    const s = this.stages[3];
    const wrap = el('section', 'rv-stage');
    wrap.dataset.stage = 'ranking';
    wrap.appendChild(el('h2', 'rv-title', `${s.title}<small>${s.sub}</small>`));
    wrap.appendChild(el('p', 'rv-lede', s.lede));

    // The ranking stage is the only point in the session where two things
    // must be compared, and it used to show only one of them: five candidate
    // pictures and none of the viewer's own work. Recovering the ideogram or
    // the sketch meant pressing BACK twice. The evidence rides along now.
    const ev = el('div', 'rv-evidence');
    ev.id = 'rv-evidence';
    wrap.appendChild(ev);
    this._nodes.evidence = ev;

    const note = el('div', 'rv-ranknote');
    note.innerHTML = `Tap to rank &middot; tap again to clear<b id="rv-rankstate" class="rv-rankstate"></b>`;
    wrap.appendChild(note);
    this._nodes.rankState = note.querySelector('#rv-rankstate');

    const grid = el('div', 'rv-grid');
    this._nodes.cands = [];
    // this.order is already independently shuffled; we iterate it as-is so the
    // DOM order IS the shuffled order and nothing re-sorts it.
    this.order.forEach((t, pos) => {
      const b = el('button', 'rv-cand');
      b.type = 'button';
      b.dataset.id = t.id;
      b.setAttribute('aria-label', t.name);
      const canvas = el('canvas', 'rv-cand-canvas');
      b.appendChild(canvas);
      b.appendChild(el('span', 'rv-cand-name', t.name));
      const rank = el('span', 'rv-cand-rank', String(pos + 1));
      rank.dataset.role = 'rank';
      rank.textContent = '·';
      b.appendChild(rank);
      b.addEventListener('click', () => this.rankCandidate(t.id));
      grid.appendChild(b);
      this._nodes.cands.push({ target: t, button: b, canvas, rank, pos });
    });
    wrap.appendChild(grid);
    this._nodes.grid = grid;
    return wrap;
  }

  /**
   * Paint the five candidate thumbnails.
   *
   * Deferred to the next frame on purpose: the stage was display:none a moment
   * ago, so clientWidth/clientHeight are still 0 and painting now would size
   * the backing store wrong and leave the art stretched. Re-paints on resize
   * too, so a rotate or a window drag does not leave soft thumbnails.
   */
  _paintCandidates() {
    const paint = () => {
      if (!this._nodes.cands?.length) return;
      if (!this._nodes.cands[0].canvas.clientWidth) { requestAnimationFrame(paint); return; }
      for (const c of this._nodes.cands) paintTarget(c.canvas, c.target);
    };
    requestAnimationFrame(paint);
    if (!this._gridRO && typeof ResizeObserver !== 'undefined' && this._nodes.grid) {
      let lastW = 0;
      this._gridRO = new ResizeObserver(() => {
        const w = this._nodes.grid.clientWidth;
        if (w && w !== lastW) { lastW = w; paint(); }
      });
      this._gridRO.observe(this._nodes.grid);
    }
  }

  /* ================================================================
   * ranking behaviour
   * ================================================================ */

  /** Tap a candidate: assign the next free rank, or clear it if already ranked. */
  rankCandidate(id) {
    if (this.committed) return;
    if (this.ranking.has(id)) {
      const freed = this.ranking.get(id);
      this.ranking.delete(id);
      // Close the gap so ranks stay 1..k with no holes.
      for (const [k, v] of [...this.ranking]) if (v > freed) this.ranking.set(k, v - 1);
    } else {
      if (this.ranking.size >= this.candidateCount) return;
      this.ranking.set(id, this.ranking.size + 1);
      if (audio.ready()) audio.sfxCommit();
    }
    this._syncRanking();
    this._syncControls();
    this._onUpdate();
  }

  /**
   * Replay the viewer's own notes into the ranking stage: the two pads
   * redrawn small from their stored strokes, plus every word they tagged.
   */
  _buildEvidence() {
    const host = this._nodes.evidence;
    if (!host) return;
    host.innerHTML = '';

    const shot = (pad, label, w, h) => {
      if (!pad || pad.isEmpty()) return null;
      const fig = el('figure', 'rv-ev-shot');
      const img = document.createElement('img');
      img.src = pad.toDataURL();
      img.alt = label;
      img.width = w; img.height = h;
      fig.appendChild(img);
      fig.appendChild(el('figcaption', '', label));
      return fig;
    };

    const ideo = shot(this.pads.ideogram, 'Ideogram', 96, 72);
    const sk = shot(this.pads.sketch, 'Sketch', 128, 96);
    if (ideo) host.appendChild(ideo);
    if (sk) host.appendChild(sk);

    const words = [];
    for (const cat of SENSORY_CATEGORIES) {
      for (const w of this.impressions[cat.id]) words.push(w);
    }
    if (words.length) {
      const box = el('div', 'rv-ev-words');
      for (const w of words) box.appendChild(el('span', 'rv-ev-word', w));
      host.appendChild(box);
    }

    if (!ideo && !sk && !words.length) {
      host.appendChild(el('p', 'rv-ev-empty', 'You recorded no impressions this session.'));
    }
  }

  _syncRanking() {
    for (const c of this._nodes.cands) {
      const r = this.ranking.get(c.target.id);
      c.rank.textContent = r ? String(r) : '·';
      c.button.classList.toggle('ranked', !!r);
      c.button.classList.toggle('first', r === 1);
    }
    const firstId = this.firstChoiceId();
    const first = firstId ? this.order.find((t) => t.id === firstId) : null;
    if (this._nodes.rankState) {
      this._nodes.rankState.textContent = first
        ? `first choice: ${first.name}${this.ranking.size < this.candidateCount ? ` (${this.ranking.size}/${this.candidateCount} ranked)` : ' \u2014 full ranking'}`
        : 'no first choice yet';
    }
  }

  firstChoiceId() {
    for (const [id, r] of this.ranking) if (r === 1) return id;
    return null;
  }

  /* ================================================================
   * stage navigation
   * ================================================================ */

  get stage() { return this.stages[this.stageIndex]; }

  _goto(i, initial = false) {
    const next = Math.max(0, Math.min(this.stages.length - 1, i));
    if (!initial) {
      const id = this.stages[this.stageIndex].id;
      this.stageTimes[id] = (this.stageTimes[id] || 0) + (Date.now() - this.stageEnteredAt);
    }
    this.stageIndex = next;
    this.stageEnteredAt = Date.now();

    const sections = this._nodes.stages.children;
    for (let k = 0; k < sections.length; k++) sections[k].classList.toggle('on', k === next);
    for (const li of this._nodes.rail.children) {
      const k = Number(li.dataset.i);
      li.classList.toggle('done', k < next);
      li.classList.toggle('now', k === next);
    }

    const id = this.stage.id;
    // A pad inside a display:none stage measured 0x0, so re-measure on entry.
    if (id === 'ideogram') { this.pads.ideogram._resize(); this._startIdeogramTimer(); }
    else this._stopTimer();
    if (id === 'sketch') this.pads.sketch._resize();
    if (id === 'ranking') {
      this._paintCandidates();
      this._buildEvidence();   // on entry: the pads are only filled by now
      this._syncRanking();
      this.ctx.director?.pushIn?.(0.18, new THREE.Vector3(0, 1.0, -0.4), 5);
    } else {
      this.ctx.director?.release?.(3);
    }
    this._syncControls();
    this.onStage?.(id, next);
    this._onUpdate();
    // Each stage starts at its own top, not wherever the last one was scrolled.
    sections[next].scrollTop = 0;
  }

  nextStage() {
    if (this.stageIndex >= this.stages.length - 1) { this.commit(); return; }
    if (!this._canLeaveStage()) return;
    this._goto(this.stageIndex + 1);
    if (audio.ready()) audio.sfxDeal();
  }

  prevStage() {
    if (this.stageIndex === 0) return;
    if (this.committed) return;
    this._goto(this.stageIndex - 1);
  }

  /**
   * Gating is deliberately soft. The protocol wants every stage attempted, but
   * a viewer with no pointer device must not be trapped, so the only hard
   * requirement is a first choice at the ranking stage — without that there is
   * nothing to score.
   */
  _canLeaveStage() {
    const id = this.stage.id;
    if (id === 'ideogram' && this.pads.ideogram.isEmpty()) {
      this._nudge('Let the pen move — one quick stroke is enough');
      return false;
    }
    if (id === 'sketch' && this.pads.sketch.isEmpty()) {
      this._nudge('Put something down, however rough');
      return false;
    }
    return true;
  }

  _nudge(text) {
    if (!this._nodes.hint) return;
    this._nodes.hint.textContent = text;
    this._nodes.hint.style.color = 'var(--amber,#e8a33d)';
    clearTimeout(this._nudgeTimer);
    this._nudgeTimer = setTimeout(() => {
      this._nudgeTimer = null;          // release the lock, or the hint freezes
      this._nodes.hint.style.color = '';
      this._syncControls();
    }, 1800);
  }

  _syncControls() {
    if (!this._nodes.next) return;
    const id = this.stage.id;
    const last = this.stageIndex === this.stages.length - 1;
    this._nodes.prev.disabled = this.stageIndex === 0 || this.committed;
    this._nodes.next.textContent = this.committed ? 'Session complete'
      : last ? 'Commit ranking' : 'Next stage';
    if (last) {
      const ok = !!this.firstChoiceId() && !this.committed;
      this._nodes.next.disabled = !ok;
      this._setHint(this.committed ? 'Committed.' :
        ok ? 'Your ranking is sealed against the target when you commit'
           : 'Tap your strongest match first');
    } else {
      this._nodes.next.disabled = false;
      if (id === 'ideogram') this._setHint('One reflexive stroke, then move on');
      else if (id === 'sensory') {
        const n = this.impressionCount();
        this._setHint(n ? `${n} impression${n === 1 ? '' : 's'} recorded` : 'Tag anything that comes through');
      } else if (id === 'sketch') this._setHint('Undo and clear are there if you need them');
    }
  }

  /**
   * A nudge owns the hint line for its 1.8s; the stage hint is restored by the
   * _syncControls() call at the end of the nudge, so we simply skip writes
   * while a nudge is up rather than queueing them.
   */
  _setHint(text) {
    if (!this._nodes.hint || this._nudgeTimer) return;
    this._nodes.hint.textContent = text;
  }

  impressionCount() {
    return Object.values(this.impressions).reduce((a, v) => a + v.length, 0);
  }

  /** Push a snapshot to whoever is drawing the chrome. Safe when ctx is bare. */
  _onUpdate() {
    this.ctx.onUpdate?.(this.snapshot());
  }

  _onKey(e) {
    if (this.committed || !this.root || !this.root.isConnected) return;
    if (e.target && /^(INPUT|TEXTAREA)$/.test(e.target.tagName)) return;
    if (this.stage.id === 'ranking' && /^[1-5]$/.test(e.key)) {
      const c = this._nodes.cands[Number(e.key) - 1];
      if (c) { e.preventDefault(); this.rankCandidate(c.target.id); }
      return;
    }
    if (e.key === 'Enter' && !this._nodes.next.disabled) { e.preventDefault(); this.nextStage(); }
  }

  /* ================================================================
   * commit and score
   * ================================================================ */

  /** Lock the ranking in, score it, and resolve finish(). */
  commit() {
    if (this.committed) return;
    const firstId = this.firstChoiceId();
    if (!firstId) { this._nudge('Pick a first choice before committing'); return; }

    this.committed = true;
    this.committedAt = Date.now();
    const id = this.stages[this.stageIndex].id;
    this.stageTimes[id] = (this.stageTimes[id] || 0) + (Date.now() - this.stageEnteredAt);

    // A hit is first place and nothing else.
    this.hit = firstId === this.target.id;
    this.hits = this.hit ? 1 : 0;
    this.rankOfTarget = this.ranking.get(this.target.id) || null;
    this.finished = true;

    for (const c of this._nodes.cands) {
      c.button.disabled = true;
      const isTrue = c.target.id === this.target.id;
      c.button.classList.toggle('rv-true', isTrue);
      c.button.classList.toggle('rv-dim', !isTrue && this.ranking.get(c.target.id) !== 1);
    }
    // The outcome line must win, so clear any nudge that still holds the hint.
    clearTimeout(this._nudgeTimer);
    this._nudgeTimer = null;
    this._syncControls();
    this._setHint(this.hit ? 'First place — that is a hit' : `The target was ${this.target.name}`);

    this._juice();
    this._onUpdate();
    this._resolveDone(this.report());
  }

  _juice() {
    const { particles, floatText, director } = this.ctx;
    // Math.random here is cosmetic jitter on a particle anchor and nothing else.
    const anchor = new THREE.Vector3((Math.random() - 0.5) * 0.1, 0.95, -0.5);
    if (this.hit) {
      audio.sfxHit?.(0);
      director?.addTrauma?.(0.42);
      particles?.burst?.(anchor, {
        count: 90, speed: 3.6, spread: 1.8, size: 12, life: 1.2,
        colors: [0x49d17c, 0xe8a33d, 0xfff0cf, 0x9fe8bd],
      });
      floatText?.spawn?.(new THREE.Vector3(0, 1.62, -0.5), 'HIT', { kind: 'hit' });
    } else {
      audio.sfxMiss?.();
      director?.addTrauma?.(0.08);
      floatText?.spawn?.(new THREE.Vector3(0, 1.62, -0.5), this.target.name.toUpperCase(), { kind: 'miss' });
    }
    floatText?.spawn?.(new THREE.Vector3(-1.0, 1.95, -0.5), this.coordinate, { kind: 'coord', dur: 0.8, drift: 0.7 });
  }

  /* ================================================================
   * reporting
   * ================================================================ */

  snapshot() {
    return {
      mode: MODE,
      coordinate: this.coordinate,
      stage: this.stage.id,
      stageIndex: this.stageIndex,
      stageCount: this.stages.length,
      impressions: this.impressions,
      impressionCount: this.impressionCount(),
      ranked: this.ranking.size,
      firstChoice: this.firstChoiceId(),
      committed: this.committed,
      trials: TRIALS,
      hits: this.hits,
      chance: this.chance,
    };
  }

  /** Same shape as ZenerRun.report(), plus the remote-viewing specifics. */
  report() {
    const base = summarize(this.hits, TRIALS, this.chance);
    const ranking = this.order.map((t, pos) => ({
      id: t.id, name: t.name, position: pos + 1,
      rank: this.ranking.get(t.id) || null,
      isTarget: t.id === this.target.id,
    }));
    const firstId = this.firstChoiceId();
    const chosen = firstId ? this.order.find((t) => t.id === firstId) : null;
    return {
      ...base,
      mode: MODE,
      trials: TRIALS,
      hits: this.hits,
      chance: this.chance,
      hit: !!this.hit,
      coordinate: this.coordinate,
      rankOfTarget: this.rankOfTarget ?? null,
      target: {
        id: this.target.id, name: this.target.name,
        describe: this.target.describe, tags: this.target.tags.slice(),
      },
      firstChoice: chosen ? { id: chosen.id, name: chosen.name } : null,
      candidates: ranking,
      ranking,
      results: [{
        guess: chosen?.id ?? null, target: this.target.id,
        hit: !!this.hit, commitment: this.commitment,
      }],
      impressions: JSON.parse(JSON.stringify(this.impressions)),
      impressionCount: this.impressionCount(),
      matchedTags: this._matchedTags(),
      ideogram: {
        png: this.pads.ideogram?.toDataURL() ?? null,
        vector: this.pads.ideogram?.toJSON() ?? null,
        strokes: this.pads.ideogram?.strokeCount() ?? 0,
      },
      sketch: {
        png: this.pads.sketch?.toDataURL() ?? null,
        vector: this.pads.sketch?.toJSON() ?? null,
        strokes: this.pads.sketch?.strokeCount() ?? 0,
      },
      stageTimes: { ...this.stageTimes },
      durationMs: (this.committedAt || Date.now()) - this.startedAt,
      sealedAt: this.sealedAt,
      // The proof. Recompute SHA-256(salt + ':' + payload) and compare.
      proof: [{ i: 0, ...this.commitment.reveal }],
    };
  }

  /**
   * Which of the viewer's words also appear in the target's own tag list.
   * Shown as feedback only — it is NOT scored, because the tag lists are
   * hand-written and scoring them would be scoring my vocabulary, not psi.
   */
  _matchedTags() {
    const mine = new Set(Object.values(this.impressions).flat());
    return this.target.tags.filter((t) => mine.has(t.toLowerCase()));
  }

  /**
   * Resolves with the report once the viewer commits a ranking. Logs the
   * session to the career log unless opts.autoLog was false — if you log it
   * yourself in main.js as well, the career statistics will double-count.
   */
  async finish() {
    const rep = await this._done;
    if (this.autoLog && !this._logged) {
      this._logged = true;
      logSession({
        mode: MODE,
        trials: TRIALS,
        hits: this.hits,
        chance: this.chance,
        detail: {
          coordinate: rep.coordinate,
          targetId: rep.target.id,
          firstChoiceId: rep.firstChoice?.id ?? null,
          rankOfTarget: rep.rankOfTarget,
          candidateIds: rep.candidates.map((c) => c.id),
          impressionCount: rep.impressionCount,
          matchedTags: rep.matchedTags,
          ideogramStrokes: rep.ideogram.strokes,
          sketchStrokes: rep.sketch.strokes,
          durationMs: rep.durationMs,
          digest: this.commitment.digest,
        },
      });
    }
    return rep;
  }

  dispose() {
    this._stopTimer();
    this._gridRO?.disconnect();
    clearTimeout(this._nudgeTimer);
    if (this._keyHandler) globalThis.removeEventListener('keydown', this._keyHandler);
    this.pads.ideogram?.dispose();
    this.pads.sketch?.dispose();
    this.root?.remove();
    this.ctx.director?.release?.(4);
    // An unmounted run must never leave finish() hanging forever.
    if (!this.finished) this._resolveDone(null);
  }
}

/* ================================================================
 * helpers main.js can use for the result modal
 * ================================================================ */

/**
 * The reveal block: the true target drawn large, the viewer's own ideogram and
 * sketch beside it, and which of the target's tags the viewer actually named.
 * Returns a detached element — drop it into the result panel.
 */
export function buildRevealBlock(report) {
  const wrap = el('div', 'rv-reveal');
  const canvas = el('canvas', 'rv-reveal-art');
  wrap.appendChild(canvas);
  wrap.appendChild(el('h3', 'rv-reveal-name',
    `${report.target.name}${report.hit ? '' : ` &middot; you ranked it ${report.rankOfTarget ? ORDINAL[report.rankOfTarget] : 'nowhere'}`}`));
  wrap.appendChild(el('p', 'rv-reveal-desc', report.target.describe));

  if (report.target.tags?.length) {
    const tags = el('div', 'rv-tags');
    const hit = new Set(report.matchedTags || []);
    for (const t of report.target.tags) {
      const c = el('span', `rv-tag${hit.has(t) ? ' match' : ''}`, t);
      tags.appendChild(c);
    }
    wrap.appendChild(tags);
  }

  if (report.ideogram?.png || report.sketch?.png) {
    const side = el('div', 'rv-sidebyside');
    for (const [key, caption] of [['ideogram', 'Your ideogram'], ['sketch', 'Your sketch']]) {
      if (!report[key]?.png) continue;
      const fig = el('figure');
      const img = el('img');
      img.src = report[key].png;
      img.alt = caption;
      fig.appendChild(img);
      fig.appendChild(el('figcaption', null, caption));
      side.appendChild(fig);
    }
    wrap.appendChild(side);
  }

  // Paint once the element has a measurable width.
  const paint = () => {
    const t = TARGETS.find((x) => x.id === report.target.id);
    if (!t) return;
    if (!canvas.clientWidth) { requestAnimationFrame(paint); return; }
    paintTarget(canvas, t);
  };
  requestAnimationFrame(paint);
  return wrap;
}

/** Re-check a finished run's commitment. Pure verification; no side effects. */
export async function verifyRun(report) {
  const p = report?.proof?.[0];
  if (!p) return false;
  if (!p.payload.includes(`target=${report.target.id}`)) return false;
  if (!p.payload.startsWith(`rv:${report.coordinate}:`)) return false;
  return verify(p);
}

export default RemoteViewRun;
